Implementação de namespace filtros
EESC-USP-TUPA/TAL pull request #7
Opened 2022-02-02 02:15 UTC by AndreyCortez

Fix #4 

Ao invés de uma classe eu acho que os filtros cabem mais a um namespace, onde podemos colocar filtros de vários tipos que podem ser usados sem a necessidade de ficar declarando e construindo uma classe para cada um deles, no arquivo Teste.cpp eu coloquei um exemplo de como cada um deles funcionaria.
Eu ainda não fiz nenhum tipo de validação pra saber se eles tão funcionando direito, mas ao que parece está tudo certo

2022-02-02 02:44 UTC, VitorCMatias commented
> Fix #4
> 
> Ao invés de uma classe eu acho que os filtros cabem mais a um namespace, onde podemos colocar filtros de vários tipos que podem ser usados sem a necessidade de ficar declarando e construindo uma classe para cada um deles, no arquivo Teste.cpp eu coloquei um exemplo de como cada um deles funcionaria. Eu ainda não fiz nenhum tipo de validação pra saber se eles tão funcionando direito, mas ao que parece está tudo certo

@AndreyCortez concordo com o que vc disse, os namespaces fazem mais sentido. Além disso, é assim que muitas pessoas têm implementado na internet pelo que eu pesquisei.

2022-02-02 02:52 UTC, VitorCMatias commented
@AndreyCortez  mesmo tendo feito isso no .hpp, coloca comentários do tipo /*......*/ explicando o que a função faz no .cpp ou tenta colocar nomes de funções mais semânticos.

2022-02-02 03:18 UTC, VitorCMatias requested changes
coloquei no código sugestões de mudança que podem facilitar o entendimento do código. Outra coisa tenta ver s ao invés de usar o int normal, não tem como usarmos tipo o uint_8_t para tamanhos, por exemplo, (mas isso pode ser aplicado em outros lugares do código também), pois assim economizamos um pouco de RAM do micro. Vc também declarou variáveis em laços o que não é uma boa prática. Quando vc mandar mais de um commit do mesmo assunto, tipo agora que vc só apagou um arquivo, por exemplo, use o comando squash do git.

2022-02-02 03:18 UTC, VitorCMatias commented on Filtros/Filtros.cpp
> +    std::vector<float> MME(std::vector<float> vetor_dados, int tamanho_da_amostra)
```suggestion
    std::vector<float> media_movel_exponencial(std::vector<float> dados, int tamanho_da_amostra)
    /* 
    Media movel exponencial, um tipo de media onde os dados mais recentes possuem um peso maior
    */
```

2022-02-02 03:18 UTC, VitorCMatias commented on Filtros/Filtros.cpp
> +    std::vector<float> MMS(std::vector<float> vetor_dados, int tamanho_da_amostra)
```suggestion
    std::vector<float> medial_movel_simples(std::vector<float> dados, int tamanho_da_amostra)
    /*Media movel simples para atenuar variações bruscas da amostragem*/
```

2022-02-02 03:18 UTC, VitorCMatias commented on Filtros/Filtros.cpp
> +            float acc = 0;
Declaração de variável dentro e laço é um problema, pois ele vai ficar toda hora alocando memória do micro.

2022-02-02 16:40 UTC, AndreyCortez commented
Sobre o bagulho de usar o uint8_t, a gente tem alguma estimativa do tamanho máximo do vetor que o código vai processar?

2022-02-03 16:30 UTC, murilo-toddy commented
> Sobre o bagulho de usar o uint8_t, a gente tem alguma estimativa do tamanho máximo do vetor que o código vai processar?

Uma opção é poder passar o tipo de dado também como parâmetro. Em geral, ADC é sempre uint32_t e o resto uint16_t.

Eu nunca fui muito a fundo com namespace, mas ele não pode ter variáveis locais né? Me incomoda um pouco ter que passar o vetor de pesos em toda iteração pra média móvel ponderada, por exemplo. 

Se tivesse como "instanciar um namespace" com parâmetros na inicialização acho que seria legal (por isso sugeri o uso de classes). O que pode funcionar é criar uma classe que usa as funções do namespace (não sei se tou falando bosta), ou talvez deixar todos os parâmetros relativos ao filtro internos na classe de cada sensor (o que permitiria a gente filtrar cada dado de um jeito, algo que pode ser interessante)

2022-02-03 17:22 UTC, VitorCMatias commented
> 

O name space serve para evitar conflitos de nome, tipo vc pode ter 2 funções com a mesma assinatura e nome em name spaces diferentes. Tipo:


`namespace xololo{ foo(); } .........  xololo::foo();`

2022-02-04 01:24 UTC, AndreyCortez commented
Eu fiz uma pequena mudança que permite que a gnt use as funções desse namespace com vetores de vários tipos diferentes de conteúdos, por exemplo, a função de media móvel simples pode ser usada em um vetor de float ou de uint16_t sem nenhuma mudança no código (ver Teste.cpp), dando uma olhada na Filtros.cpp da pra ter mais ou menos uma ideia de como isso funciona, mas não sei se eu fiz uma implementação boa. Tbm coloquei header guards no Filtros.hpp

2022-02-10 23:43 UTC, merged